### ISSUE TITLE
Building sonar-scanner-action takes very long

### ISSUE THREAD

**Issue by tom-brosch** [philips-software/sonar-scanner-action#104]
We are using the sonar-scaner-action in our CI/CD pipeline and this action is always rebuild as one of the first steps in the pipeline. Currently, this takes quite long (more than 15 minutes; see screenshot), which slows down the entire pipeline by quite a bit. Is there a way to speed things up?

![image](https://user-images.githubusercontent.com/71647919/142178740-4ddec849-60db-4b6c-933b-2862fe8e8d5d.png)

**Comment by npalm** [comment]
Sorry for the late response, using the action should not take long. The only part that could talke long is fetching the docker image. The build is nothing more than copy a bunch of files.

**Comment by tom-brosch** [comment]
Recent builds take about 1 minute to build the action. Closing the issue for now as it doesn't occur anymore.
